services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USERNAME
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USERNAME", "-d", "$POSTGRES_DB" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: [ postgres ]

volumes:
  haproxy:
