name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: checkout badges branch into 'badges' directory
        uses: actions/checkout@v4
        with:
          ref: badges
          path: badges

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: gradlew build
        run: ./gradlew clean ktlintCheck build

      - name: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Commit the badge (if it changed)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain *.svg *.json` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add *.svg *.json
            git commit -m "Autogenerated JaCoCo coverage badges"
            git push
          fi

      - name: dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
